const menu = [
  {
    id: 1,
    title: 'Caldo (meio)',
    category: 'café da manhá',
    price: 3.99,
    img: './images/item-1.jpeg',
    desc: `Saboroso, quente, nutritivo, reconfortante, tradicional, delicioso.`,
  },
  {
    id: 2,
    title: 'caldo (grande)',
    category: 'café da manhá',
    price: 6.99,
    img: './images/item-2.jpeg',
    desc: `Saboroso, quente, nutritivo, reconfortante, tradicional, delicioso. `,
  },
  {
    id: 3,
    title: 'café (xícara pequena)',
    category: 'bebidas',
    price: 0.99,
    img: './images/item-3.jpeg',
    desc: `Aromático, quente, encorpado, estimulante, acolhedor, saboroso.`,
  },
  {
    id: 4,
    title: 'café (xícara grande)',
    category: 'bebidas',
    price: 1.99,
    img: './images/item-4.jpeg',
    desc: `Aromático, quente, encorpado, estimulante, acolhedor, saboroso. `,
  },
  {
    id: 5,
    title: 'cafè con leite (xícara)',
    category: 'bebidas',
    price: 2.49,
    img: './images/item-5.jpeg',
    desc: `Cremoso, suave, quente, reconfortante, equilibrado, delicioso.`,
  },
  {
    id: 6,
    title: 'cafè con leite (copo grande)',
    category: 'bebidas',
    price: 2.99,
    img: './images/item-6.jpeg',
    desc: `Cremoso, suave, quente, reconfortante, equilibrado, delicioso.`,
  },
  {
    id: 7,
    title: 'cuscuz com ovo e café',
    category: 'café da manhá',
    price: 9.99,
    img: './images/item-7.jpeg',
    desc: `Tradicional, nutritivo, saboroso, quente, energético, completo. `,
  },
  {
    id: 8,
    title: 'o leite só',
    category: 'café da manhá',
    price: 2.49,
    img: './images/item-8.jpeg',
    desc: `Tradicional, nutritivo, saboroso, quente, energético, completo. `,
  },
  {
    id: 9,
    title: 'bolo',
    category: 'café da manhá',
    price: 2.49,
    img: './images/item-9.jpeg',
    desc: `Doce, macio, saboroso, fofo, caseiro, delicioso.`,
  },
];
export default menu;
