const menu = [
  {
    id: 1,
    title: 'Caldo (meio)',
    category: 'café da manhá',
    price: 3.99,
    img: './images/item-1.jpeg',
    desc: `Saboroso, quente, nutritivo, reconfortante, tradicional, delicioso.`,
  },
  {
    id: 2,
    title: 'caldo (grande)',
    category: 'café da manhá',
    price: 6.99,
    img: './images/item-2.jpeg',
    desc: `Saboroso, quente, nutritivo, reconfortante, tradicional, delicioso. `,
  },
  {
    id: 3,
    title: 'café (xícara pequena)',
    category: 'bebidas',
    price: 0.99,
    img: './images/item-3.jpeg',
    desc: `Aromático, quente, encorpado, estimulante, acolhedor, saboroso.`,
  },
  {
    id: 4,
    title: 'café (xícara grande)',
    category: 'bebidas',
    price: 1.99,
    img: './images/item-4.jpeg',
    desc: `Aromático, quente, encorpado, estimulante, acolhedor, saboroso. `,
  },
  {
    id: 5,
    title: 'cafè con leite (xícara)',
    category: 'bebidas',
    price: 2.49,
    img: './images/item-5.jpeg',
    desc: `Cremoso, suave, quente, reconfortante, equilibrado, delicioso.`,
  },
  {
    id: 6,
    title: 'cafè con leite (copo grande)',
    category: 'bebidas',
    price: 2.99,
    img: './images/item-6.jpeg',
    desc: `Cremoso, suave, quente, reconfortante, equilibrado, delicioso.`,
  },
  {
    id: 7,
    title: 'cuscuz com ovo e café',
    category: 'café da manhá',
    price: 9.99,
    img: './images/item-7.jpeg',
    desc: `Tradicional, nutritivo, saboroso, quente, energético, completo. `,
  },
  {
    id: 8,
    title: 'o leite só',
    category: 'café da manhá',
    price: 2.49,
    img: './images/item-8.jpeg',
    desc: `Tradicional, nutritivo, saboroso, quente, energético, completo. `,
  },
  {
    id: 9,
    title: ' bolo doze',
    category: 'café da manhá',
    price: 2.49,
    img: './images/item-9.jpeg',
    desc: `Doce, macio, saboroso, fofo, caseiro, delicioso.`,
  },
  {
    id: 10,
    title: 'mocoto',
    category: 'almoço',
    price: 6.99,
    img: './images/item-9.jpeg',
    desc: `Acompanhamiento: arroz, farofa, macarrão, figado`,
  },
  {
    id: 11,
    title: 'frango ao molho',
    category: 'almoço',
    price: 14.99,
    img: './images/item-9.jpeg',
    desc: `Acompanhamiento: arroz, farofa, macarrão, figado`,
  },
  {
    id: 12,
    title: 'bisteca (porco, boi e de figado)',
    category: 'almoço',
    price: 14.99,
    img: './images/item-9.jpeg',
    desc: `Acompanhamiento: arroz, farofa, macarrão, figado`,
  },
  {
    id: 13,
    title: 'suco (copo)',
    category: 'bebidas',
    price: 2.99,
    img: './images/item-9.jpeg',
    desc: `natural, concentrado, integral, pasteurizado, orgânico.`,
  },
  {
    id: 14,
    title: 'coca zero',
    category: 'bebidas',
    price: 4.99,
    img: './images/item-9.jpeg',
    desc: `refrigerante, gaseificado, doce, refrescante`,
  },
  {
    id: 15,
    title: 'coca normal',
    category: 'bebidas',
    price: 4.99,
    img: './images/item-9.jpeg',
    desc: `refrigerante, gaseificado, doce, refrescante`,
  },
  {
    id: 16,
    title: 'fanta laranja',
    category: 'bebidas',
    price: 4.99,
    img: './images/item-9.jpeg',
    desc: `refrigerante, gaseificado, doce, refrescante`,
  },
  {
    id: 17,
    title: 'agua',
    category: 'bebidas',
    price: 1.99,
    img: './images/item-9.jpeg',
    desc: `pura, transparente, inodora, insípida, esencial.`,
  },
];
export default menu;
